version: '3.8'

services:
  frontend:
    container_name: sveltekit_container
    build: 
      context: ./frontend # Path ke folder frontend yang berisi Dockerfile Svelte
      dockerfile: Dockerfile
    ports:
      - "3000:3000"       # Map port 3000 di host ke port 3000 di kontainer Svelte
    # environment:
    #   # Contoh variabel lingkungan untuk Svelte (jika perlu)
    #   # Misal, URL API backend Anda
    # BACKEND_API: http://app:8080/
    networks:
      - fullstack
    volumes:
      - ./frontend/:/app
    depends_on:
      - app
    # command: npm run dev -- --host 0.0.0.0
  app:
    container_name: golang_container
    build: 
      context: ./beinventory
      dockerfile: Dockerfile
    env_file: 
      - ./beinventory/.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      DATABASE_HOST: ${DB_HOST}
      DATABASE_PORT: ${DB_PORT}
    ports:
      - "8080:8080"
    # restart: on-failure
    volumes:
      - ./beinventory/:/app
    depends_on:
      - postgresdb
    networks:
      - fullstack
    deploy:
      resources:
        limits:
          memory: 1g
        reservations:
          memory: 512M
  # nginx:
  #   build:
  #     context: ./nginx
  #     dockerfile: Dockerfile
  #   ports:
  #     - "80:80" # Expose port 80 untuk akses web
  #   depends_on:
  #     - frontend
  #     - app
  #   restart: always

  postgresdb:
    container_name: postgres_container
    image: postgres:latest
    env_file: 
      - ./beinventory/.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      DATABASE_HOST: ${DB_HOST}
    ports:
      - "5432:5432"
    volumes:
      - beinventory_pgdata:/var/lib/postgresql/data
    networks:
      - fullstack
    deploy:
      resources:
        limits:
          memory: 1g
        reservations:
          memory: 512M

volumes:
  beinventory_pgdata:
    external: true

networks:
  fullstack:
    driver: bridge 